liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml

mots:
    ivrApiKey: ${ivrApiKey}
    resourceId: mots
    loadLocations: ${loadLocations}

security:
    oauth2:
        client:
            authentication-scheme: header

token:
    validitySeconds: 600

server:
    port: ${tomcatServerPort}
    ssl:
        enabled: ${sslEnabled:false}
        key-alias: ${keyAlias:""}
        key-store: ${keyStore:""}
        key-store-password: ${keyStorePassword:""}

logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n'

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: ${databasePassword}
        url: ${databaseUrl}
        username: ${databaseUser}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
